# Header
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  Github:
    url: https://bomee88.github.io/
    icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title: 

# URL of the Home page image
index_cover: /img/main.png

# Default post title
default_post_title: RLKorea

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid: 
    comment_count: 
    comment_colorscheme: 

# Google Analytics Tracking ID
google_analytics:

# Addthis ID
addthis:

# set your own favicon
favicon: /img/favicon.ico

# Social Accounts
twitter_url:
twitter_handle:
facebook_url:
github_url: 
gitlab_url:
linkedin_url:
mailto: bomee88@naver.com

marked:
  gfm: true # GitHub flavored markdown 지원
  pedantic: false # 오리지널 마크다운 사용
  sanitize: false # HTML 무시
  tables: true # GFM 테이블 지원
  breaks: true # GFM
  smartLists: true # 오리지널 마크다운보다 스마트한 리스트
  smartypants: true # Use "smart" typograhic punctuation for things like quotes and dashes.
  modifyAnchors: '' # Use for transform anchorIds. if 1 to lowerCase and if 2 to upperCase.
  autolink: true # 오토링크 지원. 텍스트에서 링크를 자동으로 인식.